server:
  port: 8080

management:
  server:
    port: 8080

spring:
  application:
    name: demo-api-service
    description: Demo version of API service
    version: ${version}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /api-docs
